### ISSUE TITLE
CSDL và Giao diện không khớp [!important]

### ISSUE THREAD

**Issue by NPNKhoa** [QBitGenZ/mypham-server#10]
Thiếu brand, capacity,...
![image](https://github.com/QBitGenZ/mypham-server/assets/118678726/845ca15a-e9ea-4434-9f55-d01c9b94c626)
![image](https://github.com/QBitGenZ/mypham-server/assets/118678726/d23d0082-0a4d-4c0e-ab1d-e09786dd40a1)

**Comment by nntruyen027** [comment]
Chỉ ra cụ thể sự khác biệt

**Comment by NPNKhoa** [comment]
resolved

**Comment by NPNKhoa** [comment]
ok
