### ISSUE TITLE
Lỗi xóa loại sản phẩm

### ISSUE THREAD

**Issue by Tran-1** [QBitGenZ/mypham-server#6]
nhập token người bán và nhập id sản phẩm người bán nhưng kết quả trả về
{
    "error": "Lỗi server nội bộ"
}
![image](https://github.com/QBitGenZ/mypham-server/assets/130048265/22a5f33f-13fc-4e00-a451-50404df1f3b3)
![image](https://github.com/QBitGenZ/mypham-server/assets/130048265/d0c0ad02-a3c8-45ce-85ad-9083f6899b9b)

**Comment by nntruyen027** [comment]
Đã chỉnh sửa
